const equipo = [
    {
        id: 1,
        name: "Luis Velásquez",
        role: "CEO & Coach",
        img: "/img/reales/equipo/01_luis-velasquez_ceo-&-coach.webp",
        active: true,
    },
    {
        id: 2,
        name: "Luis Acevedo",
        role: "Gerente",
        img: "/img/reales/equipo/02_luis-acevedo_gerente.webp",
        active: true,
    },
    {
        id: 3,
        name: "Marta Clavijo",
        role: "Coordinadora de Marketing",
        img: "/img/reales/equipo/03_marta-clavijo_coordinadora_de_marketing_y_publicidad.webp",
        active: true,
    },
    {
        id: 4,
        name: "Natalia Acevedo",
        role: "Coordinadora de suplementos y estimados",
        img: "/img/reales/equipo/04_natalia-acevedo_coordinadora_de_suplemementos_y_estimados.webp",
        active: true,
    },
    {
        id: 5,
        name: "Paula Velásquez",
        role: "Manager general",
        img: "/img/reales/equipo/05_paula-velasquez_manager_general.webp",
        active: true,
    },
    {
        id: 6,
        name: "Kelvin Moya",
        role: "Ajustador publico",
        img: "/img/reales/equipo/06_kelvin-moya_ajustador_publico.webp",
        active: true,
    },
    {
        id: 7,
        name: "david zuluaga ",
        role: "suplementador",
        img: "/img/reales/equipo/07_david-zuluaga_suplementador.webp",
        active: true,
    },
    {
        id: 8,
        name: "juan c. diaz",
        role: "suplementador",
        img: "/img/reales/equipo/08_juan-c-diaz_suplementador.webp",
        active: true,
    },
    {
        id: 9,
        name: "jenifer zuluaga",
        role: "suplementadora",
        img: "/img/reales/equipo/09_jenifer-zuluaga_suplementadora.webp",
        active: true,
    },
    {
        id: 10,
        name: "alejandra ladino",
        role: "suplementadora",
        img: "/img/reales/equipo/10_alejandra-ladino_suplementadora.webp",
        active: true,
    },
    {
        id: 11,
        name: "fernanda cordoba",
        role: "suplementadora",
        img: "/img/reales/equipo/11_fernanda_cordoba_suplementadora.webp",
        active: false,
    },
    {
        id: 12,
        name: "karen gutierrez",
        role: "suplementadora",
        img: "/img/reales/equipo/12_karen_gutierrez_suplementadora.webp",
        active: true,
    },
    {
        id: 13,
        name: "lorena rojas",
        role: "suplementadora",
        img: "/img/reales/equipo/13_lorena_rojas_suplementadora.webp",
        active: true,
    },
    {
        id: 14,
        name: "miguel perdomo",
        role: "director creativo",
        img: "/img/reales/equipo/14_miguel-perdomo_director_creativo.webp",
        active: false,
    },
    {
        id: 15,
        name: "juan diaz",
        role: "diseñador grafico",
        img: "/img/reales/equipo/15_juan-s-diaz_diseñador-grafico.webp",
        active: true,
    },
    {
        id: 16,
        name: "camila guiza",
        role: "diseñadora grafica",
        img: "/img/reales/equipo/16_camila-guiza_diseñadora-grafica.webp",
        active: true,
    },
    {
        id: 17,
        name: "andersson lopez",
        role: "diseñador grafico",
        img: "/img/reales/equipo/17_andersson-lopez_diseñador-grafico.webp",
        active: true,
    },
    {
        id: 18,
        name: "jennifer murcia",
        role: "diseñadora grafica",
        img: "/img/reales/equipo/18_jennifer-murcia_diseñadora-grafica.webp",
        active: true,
    },
    {
        id: 19,
        name: "diego gomez",
        role: "ilustrador",
        img: "/img/reales/equipo/19_diego_gomez_ilustrador.webp",
        active: true,
    },
    {
        id: 20,
        name: "laura c. lombana",
        role: "diseñadora grafica",
        img: "/img/reales/equipo/20_laura_c_lombana_diseñadora_grafica.webp",
        active: true,
    },
    {
        id: 21,
        name: "raland ramirez",
        role: "diseñador grafico",
        img: "/img/reales/equipo/21_raland_ramirez_diseñador_grafico.webp",
        active: false,
    },
    {
        id: 22,
        name: "laura buelvas",
        role: "community manager",
        img: "/img/reales/equipo/22_laura-buelvas_community_manager.webp",
        active: false,
    },
    {
        id: 23,
        name: "juliana reina",
        role: "soporte en redes",
        img: "/img/reales/equipo/24_juliana_reina_soporte_en_redes.webp",
        active: true,
    },

    {
        id: 24,
        name: "natalia zamudio",
        role: "productora audiovisual",
        img: "/img/reales/equipo/25_natalia_zamudio_productora_audiovisual.webp",
        active: true,
    },
    {
        id: 25,
        name: "brayan cuadros",
        role: "productor audiovisual",
        img: "/img/reales/equipo/23_brayan_cuadros_productor_audiovisual.webp",
        active: false,
    },

    {
        id: 26,
        name: "cristyan rios",
        role: "productor audiovisual",
        img: "/img/reales/equipo/26_cristyan_rios_productor_audiovisual.webp",
        active: true,
    },
    {
        id: 27,
        name: "aura melendez",
        role: "servicio al cliente",
        img: "/img/reales/equipo/27_aura_melendez_servicio_al_cliente.webp",
        active: true,
    },
    {
        id: 28,
        name: "alejandra villalba",
        role: "consultora follow up",
        img: "/img/reales/equipo/28_alejandra_villalba_consultora_follow_up.webp",
        active: true,
    },
    {
        id: 29,
        name: "nashly herrera",
        role: "follow up",
        img: "/img/reales/equipo/29_nashly_herrera_follow_up.webp",
        active: true,
    },
    {
        id: 30,
        name: "camilo barrera",
        role: "backend developer",
        img: "/img/reales/equipo/26_camilo_barrera_backend_developer.webp",
        active: true,
    },
    {
        id: 31,
        name: "jhonny bohorquez",
        role: "front end eveloper",
        img: "/img/reales/equipo/31_jhonny_bohorquez_front_end_eveloper.webp",
        active: true,
    },
    {
        id: 32,
        name: "eduard moreno",
        role: "backend developer",
        img: "/img/reales/equipo/32_eduard_moreno_backend_developer.webp",
        active: true,
    },
    {
        id: 33,
        name: "amanda bonilla",
        role: "asistente de operaciones",
        img: "/img/reales/equipo/33_amanda-bonilla_asistente_de_operaciones.webp",
        active: true,
    },
    {
        id: 34,
        name: "adriana zuluaga",
        role: "asistente de publicidad",
        img: "/img/reales/equipo/34_adriana-zuluaga_asistente_de_publicidad.webp",
        active: true,
    },
    {
        id: 35,
        name: "angii arias",
        role: "servicio al cliente",
        img: "/img/reales/equipo/35_angii-arias_servicio_al_cliente.webp",
        active: true,
    },
    {
        id: 36,
        name: "natalia zambrano",
        role: "asistente de operaciones",
        img: "/img/reales/equipo/36_natalia_zambrano_asistente_de_operaciones.webp",
        active: true,
    },
    {
        id: 37,
        name: "byron hernandez",
        role: "asistente de operaciones",
        img: "/img/reales/equipo/37_byron_hernandez_asistente_de_operaciones.webp",
        active: true,
    },
    {
        id: 38,
        name: "lorena frayle",
        role: "asistente de operaciones",
        img: "/img/reales/equipo/38_lorena_frayle_asistente_de_operaciones.webp",
        active: true,
    },
]

export default equipo;  